def man():
    print(WHITE + " " * 100 + END)
    print(WHITE + " " * 10 + END + BLACK + ' '* 3 + END + WHITE + ' ' * 10 + END )
    print(WHITE + " " * 10 + END + BLACK + ' ' * 3 + END + WHITE + ' ' * 10 + END)
    print(WHITE + " " * 11 + END + BLACK + ' '* 1 + END + WHITE + ' ' * 11 + END )
    print(WHITE + " " * 9 + END + BLACK + ' '* 5 + END + WHITE + ' ' * 9 + END )
    print(WHITE + " " * 9 + END + BLACK + ' ' * 5 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 9 + END + BLACK + ' ' * 5 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 9 + END + BLACK + ' ' * 5 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 9 + END + BLACK + ' ' * 2 + END + WHITE + ' ' * 1 + END+ BLACK + ' ' * 2 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 9 + END + BLACK + ' ' * 2 + END + WHITE + ' ' * 1 + END + BLACK + ' ' * 2 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 1 + END + BLACK + ' ' * 10 + END + WHITE + ' ' * 1 + END + BLACK + ' ' * 2 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 1 + END + BLACK + ' ' * 2 + END + WHITE + ' ' * 9 + END + BLACK + ' ' * 2 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 3 + END + WHITE + ' ' * 9 + END + BLACK + ' ' * 2 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 3 + END + WHITE + ' ' * 9 + END + BLACK + ' ' * 2 + END + WHITE + ' ' * 9 + END)
    print(WHITE + " " * 3 + END + WHITE + ' ' * 9 + END + BLACK + ' ' * 5 + END + WHITE + ' ' * 6 + END)
    os.system('CLS')
man ()